server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registorWithEureka: false
    fetchRegistry: false
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/