server:
  port : 8761
eureka:
  instannce:
    hostname : localhost
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        